### ISSUE TITLE
你好这个项目支持oracle arm机器吗？

### ISSUE THREAD

**Issue by Checkra2n** [evendevil66/taolefan#2]

**Comment by Checkra2n** [comment]
我的机器甲骨文arm，系统是debian 10，composer不是提示错误225 就是提示Your lock file does not contain a compatible set of packages. Please run composer update.
我的环境是php 7.4

**Comment by evendevil66** [comment]
您好，您将composer.lock删除后再尝试composer install或composer update即可，之前commit忘记删除了
